-- No-op: All five product foreign key constraints below were already created
-- by the previous migration (20260715000000_add_inventory_warehouse_supplier_tables).
-- They are listed here for reference only:
--
--   product_warehouse_stocks_productId_fkey  (productId -> products.id)
--   inventory_movements_productId_fkey        (productId -> products.id)
--   product_suppliers_productId_fkey          (productId -> products.id)
--   purchase_order_items_productId_fkey       (productId -> products.id)
--   inventory_reservations_productId_fkey     (productId -> products.id)
