// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/admins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/admins">> = Specific
  const handler = {} as typeof import("../../app/admin/admins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/automation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/automation">> = Specific
  const handler = {} as typeof import("../../app/admin/automation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog">> = Specific
  const handler = {} as typeof import("../../app/admin/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories">> = Specific
  const handler = {} as typeof import("../../app/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/change-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/change-password">> = Specific
  const handler = {} as typeof import("../../app/admin/change-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/collections-showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/collections-showcase">> = Specific
  const handler = {} as typeof import("../../app/admin/collections-showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/collections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/collections">> = Specific
  const handler = {} as typeof import("../../app/admin/collections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/customers">> = Specific
  const handler = {} as typeof import("../../app/admin/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inventory/adjustments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory/adjustments">> = Specific
  const handler = {} as typeof import("../../app/admin/inventory/adjustments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inventory/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory/audit">> = Specific
  const handler = {} as typeof import("../../app/admin/inventory/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory">> = Specific
  const handler = {} as typeof import("../../app/admin/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inventory/purchase-orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory/purchase-orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/inventory/purchase-orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inventory/purchase-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory/purchase-orders">> = Specific
  const handler = {} as typeof import("../../app/admin/inventory/purchase-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inventory/suppliers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory/suppliers/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/inventory/suppliers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inventory/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory/suppliers">> = Specific
  const handler = {} as typeof import("../../app/admin/inventory/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inventory/transfers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory/transfers">> = Specific
  const handler = {} as typeof import("../../app/admin/inventory/transfers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inventory/warehouses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory/warehouses/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/inventory/warehouses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inventory/warehouses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory/warehouses">> = Specific
  const handler = {} as typeof import("../../app/admin/inventory/warehouses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/invoices">> = Specific
  const handler = {} as typeof import("../../app/admin/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/landing">> = Specific
  const handler = {} as typeof import("../../app/admin/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/admin/products/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/add">> = Specific
  const handler = {} as typeof import("../../app/admin/products/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../app/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reports/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports/customers">> = Specific
  const handler = {} as typeof import("../../app/admin/reports/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reports/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports/inventory">> = Specific
  const handler = {} as typeof import("../../app/admin/reports/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reports/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports/orders">> = Specific
  const handler = {} as typeof import("../../app/admin/reports/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reports/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports/products">> = Specific
  const handler = {} as typeof import("../../app/admin/reports/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reports/profit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports/profit">> = Specific
  const handler = {} as typeof import("../../app/admin/reports/profit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reports/revenue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports/revenue">> = Specific
  const handler = {} as typeof import("../../app/admin/reports/revenue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reports/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports/sales">> = Specific
  const handler = {} as typeof import("../../app/admin/reports/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/security/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security/api-keys">> = Specific
  const handler = {} as typeof import("../../app/admin/security/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/security/audit-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security/audit-logs">> = Specific
  const handler = {} as typeof import("../../app/admin/security/audit-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/security/device-sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security/device-sessions">> = Specific
  const handler = {} as typeof import("../../app/admin/security/device-sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/security/login-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security/login-history">> = Specific
  const handler = {} as typeof import("../../app/admin/security/login-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/security">> = Specific
  const handler = {} as typeof import("../../app/admin/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/shop">> = Specific
  const handler = {} as typeof import("../../app/admin/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/translations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/translations">> = Specific
  const handler = {} as typeof import("../../app/admin/translations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/collections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections">> = Specific
  const handler = {} as typeof import("../../app/collections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/product/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/[id]">> = Specific
  const handler = {} as typeof import("../../app/product/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop">> = Specific
  const handler = {} as typeof import("../../app/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/success">> = Specific
  const handler = {} as typeof import("../../app/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wishlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wishlist">> = Specific
  const handler = {} as typeof import("../../app/wishlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/admins/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/admins/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/admins/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/admins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/admins">> = Specific
  const handler = {} as typeof import("../../app/api/admin/admins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/api-keys">> = Specific
  const handler = {} as typeof import("../../app/api/admin/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit-logs">> = Specific
  const handler = {} as typeof import("../../app/api/admin/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/automation/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/automation/jobs">> = Specific
  const handler = {} as typeof import("../../app/api/admin/automation/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/automation/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/automation/logs">> = Specific
  const handler = {} as typeof import("../../app/api/admin/automation/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/categories/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/categories/create">> = Specific
  const handler = {} as typeof import("../../app/api/admin/categories/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/categories/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/categories/list">> = Specific
  const handler = {} as typeof import("../../app/api/admin/categories/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/change-password">> = Specific
  const handler = {} as typeof import("../../app/api/admin/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/collections/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/collections/list">> = Specific
  const handler = {} as typeof import("../../app/api/admin/collections/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/collections/picker/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/collections/picker">> = Specific
  const handler = {} as typeof import("../../app/api/admin/collections/picker/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/device-sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/device-sessions">> = Specific
  const handler = {} as typeof import("../../app/api/admin/device-sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/adjustments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/adjustments">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/adjustments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/audit">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/bulk">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/dashboard">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/movements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/movements">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/movements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/permissions">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/purchase-orders/[id]/receive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/purchase-orders/[id]/receive">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/purchase-orders/[id]/receive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/purchase-orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/purchase-orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/purchase-orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/purchase-orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/purchase-orders">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/purchase-orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/stock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/stock">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/stock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/suppliers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/suppliers/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/suppliers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/suppliers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/suppliers">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/suppliers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/transfers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/transfers">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/transfers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/warehouses/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/warehouses/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/warehouses/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inventory/warehouses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inventory/warehouses">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inventory/warehouses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/invoices/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invoices/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../app/api/admin/invoices/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/invoices/[id]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invoices/[id]/download">> = Specific
  const handler = {} as typeof import("../../app/api/admin/invoices/[id]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/invoices/by-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invoices/by-order">> = Specific
  const handler = {} as typeof import("../../app/api/admin/invoices/by-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/invoices/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invoices/create">> = Specific
  const handler = {} as typeof import("../../app/api/admin/invoices/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/invoices/export/csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invoices/export/csv">> = Specific
  const handler = {} as typeof import("../../app/api/admin/invoices/export/csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/invoices/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invoices/list">> = Specific
  const handler = {} as typeof import("../../app/api/admin/invoices/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/landing/order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/landing/order">> = Specific
  const handler = {} as typeof import("../../app/api/admin/landing/order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/landing/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/landing/publish">> = Specific
  const handler = {} as typeof import("../../app/api/admin/landing/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/landing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/landing">> = Specific
  const handler = {} as typeof import("../../app/api/admin/landing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/landing/sections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/landing/sections">> = Specific
  const handler = {} as typeof import("../../app/api/admin/landing/sections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/landing/seo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/landing/seo">> = Specific
  const handler = {} as typeof import("../../app/api/admin/landing/seo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/landing/versions/restore/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/landing/versions/restore">> = Specific
  const handler = {} as typeof import("../../app/api/admin/landing/versions/restore/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/landing/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/landing/versions">> = Specific
  const handler = {} as typeof import("../../app/api/admin/landing/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/login-history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login-history">> = Specific
  const handler = {} as typeof import("../../app/api/admin/login-history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login">> = Specific
  const handler = {} as typeof import("../../app/api/admin/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/logout">> = Specific
  const handler = {} as typeof import("../../app/api/admin/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/notifications/read-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/notifications/read-all">> = Specific
  const handler = {} as typeof import("../../app/api/admin/notifications/read-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/notifications/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/notifications/read">> = Specific
  const handler = {} as typeof import("../../app/api/admin/notifications/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/products/[id]/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/[id]/history">> = Specific
  const handler = {} as typeof import("../../app/api/admin/products/[id]/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/products/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/products/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/products/[id]/variants/[variantId]/duplicate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/[id]/variants/[variantId]/duplicate">> = Specific
  const handler = {} as typeof import("../../app/api/admin/products/[id]/variants/[variantId]/duplicate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/products/[id]/variants/[variantId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/[id]/variants/[variantId]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/products/[id]/variants/[variantId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/products/[id]/variants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/[id]/variants">> = Specific
  const handler = {} as typeof import("../../app/api/admin/products/[id]/variants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/products/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/bulk">> = Specific
  const handler = {} as typeof import("../../app/api/admin/products/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/products/check-slug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/check-slug">> = Specific
  const handler = {} as typeof import("../../app/api/admin/products/check-slug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/products/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/products/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/products/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/list">> = Specific
  const handler = {} as typeof import("../../app/api/admin/products/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/products/picker/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/picker">> = Specific
  const handler = {} as typeof import("../../app/api/admin/products/picker/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products">> = Specific
  const handler = {} as typeof import("../../app/api/admin/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/products/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/upload">> = Specific
  const handler = {} as typeof import("../../app/api/admin/products/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/rate-limits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/rate-limits">> = Specific
  const handler = {} as typeof import("../../app/api/admin/rate-limits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reports/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/customers">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reports/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reports/inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/inventory">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reports/inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reports/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/orders">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reports/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reports/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/products">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reports/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reports/profit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/profit">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reports/profit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reports/revenue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/revenue">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reports/revenue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reports/sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/sales">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reports/sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/translations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/translations">> = Specific
  const handler = {} as typeof import("../../app/api/admin/translations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/public">> = Specific
  const handler = {} as typeof import("../../app/api/health/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/create">> = Specific
  const handler = {} as typeof import("../../app/api/orders/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/get/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/get">> = Specific
  const handler = {} as typeof import("../../app/api/orders/get/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/list">> = Specific
  const handler = {} as typeof import("../../app/api/orders/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/update-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/update-status">> = Specific
  const handler = {} as typeof import("../../app/api/orders/update-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/invoices/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/invoices/download">> = Specific
  const handler = {} as typeof import("../../app/api/public/invoices/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/translations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/translations">> = Specific
  const handler = {} as typeof import("../../app/api/translations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/uploads/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/uploads/[...path]">> = Specific
  const handler = {} as typeof import("../../app/uploads/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/inventory/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/inventory">> = Specific
  const handler = {} as typeof import("../../app/admin/inventory/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reports/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../app/admin/reports/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
